name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  first-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: First Step
        run: |
          echo "First"
          echo "Second"
