name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  manual-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: First manual set
        run: |
          echo "Hello, World!"
          echo "Hello, Again!"
