name: Dependent Multi Jobs Workflow

on:
  workflow_dispatch:

jobs:
  first-workflow-job:
    runs-on: ubuntu-latest

    steps:
      - name: First Workflow Job
        run: |
          echo "Hello, First Workflow!"
  secondary-workflow-job:
    runs-on: ubuntu-latest
    needs: [first-workflow-job]

    steps:
      - name: Secondary Workflow Job
        run: |
          echo "Hello, Secondary Workflow!"

  third-workflow-job:
    runs-on: ubuntu-latest
    needs: [first-workflow-job, secondary-workflow-job]

    steps:
      - name: Third Workflow Job
        run: |
          echo "Hello, Third Workflow!"
